#server:
#  port: 80
#  servlet.context-path: /user_spring
#  servlet: 
#    encoding: 
#      charset: UTF-8
#      enabled: true
#      force: true
#
#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@124.198.47.195:1521:xe
#    username: jdeveloper00
#    password: jdeveloper00     
